### ISSUE TITLE
hr@xmind.net邮箱拒收

### ISSUE THREAD

**Issue by RK12581** [xmindltd/hiring#2]
我试了QQ邮箱和sohu邮箱投递，均被拒收

**Comment by briansun** [comment]
直接發郵件給 he@xmind.net 試試？或者把你的郵箱告訴我們。

Brian Sun

**Comment by Royalpioneer** [comment]
您好，投递给he@xmind.net的邮件也被拒收了。
我的邮箱是18340096792@sohu.com

**Comment by Royalpioneer** [comment]
不好意思误点了close，问题暂时还没解决，邮箱已留下，感谢~
